/**
 * @file reach.c
 *
 * Source code of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE reach.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#include "reach.h"
#include "type.h"
#include "networkinterface.h"
#include "C4SNet.h"
#include "distribution.h"
#include "list.h"

char *snet_reach_labels[] = {
	"E__reach__None",
	"SPDI",
	"I",
	"e",
	"size",
	"B",
	"C",
	"found"};

char *snet_reach_interfaces[] = {
	"C4SNet"};

extern void *init(void *hnd, int arg_0, void *arg_1, void *arg_2, void *arg_3);

static snet_handle_t *SNetExeRealm_create__init(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__init(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__init(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__init(snet_handle_t *handle, int arg_0, void *arg_1, void *arg_2, void *arg_3)
{
  return init(handle, arg_0, arg_1, arg_2, arg_3);
}

static snet_handle_t *SNet__reach__init(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  int stag_size = 0;
  void *field_SPDI = NULL;
  void *field_I = NULL;
  void *field_e = NULL;

  rec = SNetHndGetRecord(hnd);

  stag_size = SNetRecTakeTag(rec, T__reach__size);

  field_SPDI = SNetRefTakeData(SNetRecTakeField(rec, F__reach__SPDI));

  field_I = SNetRefTakeData(SNetRecTakeField(rec, F__reach__I));

  field_e = SNetRefTakeData(SNetRecTakeField(rec, F__reach__e));

  return(SNetCall__init(hnd, stag_size, field_SPDI, field_I, field_e));
}

extern void *reachability(void *hnd, int arg_0, void *arg_1, void *arg_2, void *arg_3, int arg_4, int arg_5, int arg_6);

static snet_handle_t *SNetExeRealm_create__reachability(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__reachability(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__reachability(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__reachability(snet_handle_t *handle, int arg_0, void *arg_1, void *arg_2, void *arg_3, int arg_4, int arg_5, int arg_6)
{
  return reachability(handle, arg_0, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
}

static snet_handle_t *SNet__reach__loop__reachability(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  int stag_size = 0;
  void *field_SPDI = NULL;
  void *field_I = NULL;
  void *field_e = NULL;
  int stag_B = 0;
  int stag_C = 0;
  int stag_found = 0;

  rec = SNetHndGetRecord(hnd);

  stag_size = SNetRecTakeTag(rec, T__reach__size);

  field_SPDI = SNetRefTakeData(SNetRecTakeField(rec, F__reach__SPDI));

  field_I = SNetRefTakeData(SNetRecTakeField(rec, F__reach__I));

  field_e = SNetRefTakeData(SNetRecTakeField(rec, F__reach__e));

  stag_B = SNetRecTakeTag(rec, T__reach__B);

  stag_C = SNetRecTakeTag(rec, T__reach__C);

  stag_found = SNetRecTakeTag(rec, T__reach__found);

  return(SNetCall__reachability(hnd, stag_size, field_SPDI, field_I, field_e, stag_B, stag_C, stag_found));
}

extern void *deallocate(void *hnd, int arg_0, void *arg_1, void *arg_2, void *arg_3, int arg_4, int arg_5, int arg_6);

static snet_handle_t *SNetExeRealm_create__deallocate(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_update__deallocate(snet_handle_t *h) { return(h); }

static snet_handle_t *SNetExeRealm_destroy__deallocate(snet_handle_t *h) { return(h); }

snet_handle_t *SNetCall__deallocate(snet_handle_t *handle, int arg_0, void *arg_1, void *arg_2, void *arg_3, int arg_4, int arg_5, int arg_6)
{
  return deallocate(handle, arg_0, arg_1, arg_2, arg_3, arg_4, arg_5, arg_6);
}

static snet_handle_t *SNet__reach__loop__deallocate(snet_handle_t *hnd)
{
  struct record *rec = NULL;
  int stag_size = 0;
  void *field_SPDI = NULL;
  void *field_I = NULL;
  void *field_e = NULL;
  int stag_B = 0;
  int stag_C = 0;
  int stag_found = 0;

  rec = SNetHndGetRecord(hnd);

  stag_size = SNetRecTakeTag(rec, T__reach__size);

  field_SPDI = SNetRefTakeData(SNetRecTakeField(rec, F__reach__SPDI));

  field_I = SNetRefTakeData(SNetRecTakeField(rec, F__reach__I));

  field_e = SNetRefTakeData(SNetRecTakeField(rec, F__reach__e));

  stag_B = SNetRecTakeTag(rec, T__reach__B);

  stag_C = SNetRecTakeTag(rec, T__reach__C);

  stag_found = SNetRecTakeTag(rec, T__reach__found);

  return(SNetCall__deallocate(hnd, stag_size, field_SPDI, field_I, field_e, stag_B, stag_C, stag_found));
}

static snet_stream_t *SNet__reach__loop___IN___FB___SL___SL___ST(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSync(in_buf, info, location, 
              SNetVariantListCreate(2, 
                SNetVariantCreate(
                  SNetIntListCreate(3, F__reach__SPDI, F__reach__I, F__reach__e), 
                  SNetIntListCreate(3, T__reach__size, T__reach__B, T__reach__C), 
                  SNetIntListCreate(0)), 
                SNetVariantCreate(
                  SNetIntListCreate(0), 
                  SNetIntListCreate(1, T__reach__found), 
                  SNetIntListCreate(0))), 
              SNetExprListCreate(2, 
                SNetEconstb( true), 
                SNetEconstb( true)));

  return (out_buf);
}

static snet_stream_t *SNet____STAR_INCARNATE_reach__loop___IN___FB___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetStarIncarnate(in_buf, info, location, 
              SNetVariantListCreate(1, 
                SNetVariantCreate(
                  SNetIntListCreate(3, F__reach__SPDI, F__reach__I, F__reach__e), 
                  SNetIntListCreate(4, T__reach__size, T__reach__B, T__reach__C, T__reach__found), 
                  SNetIntListCreate(0))), 
              SNetExprListCreate(1, 
                SNetEconstb( true)), 
              &SNet__reach__loop___IN___FB___SL___SL___ST, 
              &SNet____STAR_INCARNATE_reach__loop___IN___FB___SL___SL);

  return (out_buf);
}

static snet_stream_t *SNet__reach__loop___IN___FB___SL___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetStar(in_buf, info, location, 
              SNetVariantListCreate(1, 
                SNetVariantCreate(
                  SNetIntListCreate(3, F__reach__SPDI, F__reach__I, F__reach__e), 
                  SNetIntListCreate(4, T__reach__size, T__reach__B, T__reach__C, T__reach__found), 
                  SNetIntListCreate(0))), 
              SNetExprListCreate(1, 
                SNetEconstb( true)), 
              &SNet__reach__loop___IN___FB___SL___SL___ST, 
              &SNet____STAR_INCARNATE_reach__loop___IN___FB___SL___SL);

  return (out_buf);
}

static snet_stream_t *SNet__reach__loop___IN___FB___SL___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "reachability", 
              &SNet__reach__loop__reachability, 
              &SNetExeRealm_create__reachability, 
              &SNetExeRealm_update__reachability, 
              &SNetExeRealm_destroy__reachability, 
              SNetIntListListCreate(1, 
                SNetIntListCreate(14, tag, T__reach__size, field, F__reach__SPDI, field, F__reach__I, field, F__reach__e, tag, T__reach__B, tag, T__reach__C, tag, T__reach__found)));

  return (out_buf);
}

static snet_stream_t *SNet__reach__loop___IN___FB___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__reach__loop___IN___FB___SL___SL, 
              &SNet__reach__loop___IN___FB___SL___SR);

  return (out_buf);
}

static snet_stream_t *SNet__reach__loop___IN___FB___SR(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "deallocate", 
              &SNet__reach__loop__deallocate, 
              &SNetExeRealm_create__deallocate, 
              &SNetExeRealm_update__deallocate, 
              &SNetExeRealm_destroy__deallocate, 
              SNetIntListListCreate(2, 
                SNetIntListCreate(12, tag, T__reach__size, field, F__reach__SPDI, field, F__reach__I, field, F__reach__e, tag, T__reach__B, tag, T__reach__C), 
                SNetIntListCreate(2, tag, T__reach__found)));

  return (out_buf);
}

static snet_stream_t *SNet__reach__loop___IN___FB(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__reach__loop___IN___FB___SL, 
              &SNet__reach__loop___IN___FB___SR);

  return (out_buf);
}

static snet_stream_t *SNet__reach__loop___IN(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetFeedback(in_buf, info, location, 
              SNetVariantListCreate(2, 
                SNetVariantCreate(
                  SNetIntListCreate(3, F__reach__SPDI, F__reach__I, F__reach__e), 
                  SNetIntListCreate(3, T__reach__size, T__reach__B, T__reach__C), 
                  SNetIntListCreate(0)), 
                SNetVariantCreate(
                  SNetIntListCreate(0), 
                  SNetIntListCreate(1, T__reach__found), 
                  SNetIntListCreate(0))), 
              SNetExprListCreate(2, 
                SNetEconstb( true), 
                SNetEconstb( true)), 
              &SNet__reach__loop___IN___FB);

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_IN__reach__loop(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetNameShift(in_buf, info, location, SNET__reach__NUMBER_OF_LABELS,
              SNetVariantCreate(
                SNetIntListCreate(3, F__reach__SPDI, F__reach__I, F__reach__e), 
                SNetIntListCreate(4, T__reach__size, T__reach__B, T__reach__C, T__reach__found), 
                SNetIntListCreate(0)));

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_BODY__reach__loop(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet____SHIELD_IN__reach__loop, 
              &SNet__reach__loop___IN);

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_OUT__reach__loop(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetNameShift(in_buf, info, location, -SNET__reach__NUMBER_OF_LABELS,
              SNetVariantCreate(
                SNetIntListCreate(0), 
                SNetIntListCreate(0), 
                SNetIntListCreate(0)));

  return (out_buf);
}

static snet_stream_t *SNet__reach__loop(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;
  out_buf = SNetSerial(in_buf, info, location, 
              &SNet____SHIELD_BODY__reach__loop,
              &SNet____SHIELD_OUT__reach__loop);

  return (out_buf);
}

static snet_stream_t *SNet__reach___IN___SL(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetBox(in_buf, info, location, "init", 
              &SNet__reach__init, 
              &SNetExeRealm_create__init, 
              &SNetExeRealm_update__init, 
              &SNetExeRealm_destroy__init, 
              SNetIntListListCreate(2, 
                SNetIntListCreate(12, tag, T__reach__size, field, F__reach__SPDI, field, F__reach__I, field, F__reach__e, tag, T__reach__B, tag, T__reach__C), 
                SNetIntListCreate(2, tag, T__reach__found)));

  return (out_buf);
}

static snet_stream_t *SNet__reach___IN(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet__reach___IN___SL, 
              &SNet__reach__loop);

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_IN__reach(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetNameShift(in_buf, info, location, SNET__reach__NUMBER_OF_LABELS,
              SNetVariantCreate(
                SNetIntListCreate(3, F__reach__SPDI, F__reach__I, F__reach__e), 
                SNetIntListCreate(1, T__reach__size), 
                SNetIntListCreate(0)));

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_BODY__reach(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetSerial(in_buf, info, location, 
              &SNet____SHIELD_IN__reach, 
              &SNet__reach___IN);

  return (out_buf);
}

static snet_stream_t *SNet____SHIELD_OUT__reach(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;

  out_buf = SNetNameShift(in_buf, info, location, -SNET__reach__NUMBER_OF_LABELS,
              SNetVariantCreate(
                SNetIntListCreate(0), 
                SNetIntListCreate(0), 
                SNetIntListCreate(0)));

  return (out_buf);
}

snet_stream_t *SNet__reach___reach(snet_stream_t *in_buf, snet_info_t *info, int location)
{
  snet_stream_t *out_buf = NULL;
  out_buf = SNetSerial(in_buf, info, location, 
              &SNet____SHIELD_BODY__reach,
              &SNet____SHIELD_OUT__reach);

  return (out_buf);
}

int SNetNetToId(snet_startup_fun_t fun)
{
  if (fun == &SNet__reach__loop___IN___FB___SL___SL___ST) {
    return 1;
  }

  return -1;
}

snet_startup_fun_t SNetIdToNet(int id)
{
  if (id == 1) {
    return &SNet__reach__loop___IN___FB___SL___SL___ST;
  }

  return NULL;
}

int SNetMain__reach(int argc, char* argv[])
{
  int ret = 0;

  C4SNetInit(I__reach__C4SNet, 0);
  
  ret = SNetInRun(argc, argv,
              snet_reach_labels,
              SNET__reach__NUMBER_OF_LABELS,
              snet_reach_interfaces,
              SNET__reach__NUMBER_OF_INTERFACES,
              SNet__reach___reach);

  SNetInterfacesDestroy();

  return( ret);
}

