/**
 * @file reach.h
 *
 * Header definitions of compiled snet-file for runtime.
 *
 * THIS FILE HAS BEEN GENERATED.
 * DO NOT EDIT THIS FILE.
 * EDIT THE ORIGINAL SNET-SOURCE FILE reach.snet INSTEAD!
 *
 * ALL CHANGES MADE TO THIS FILE WILL BE OVERWRITTEN!
 *
*/

#ifndef _REACH_H_
#define _REACH_H_

#include "snetentities.h"
#include "distribution.h"

#define E__reach__NONE 0
#define F__reach__SPDI 1
#define F__reach__I 2
#define F__reach__e 3
#define T__reach__size 4
#define T__reach__B 5
#define T__reach__C 6
#define T__reach__found 7

#define SNET__reach__NUMBER_OF_LABELS 8


#define I__reach__C4SNet 0

#define SNET__reach__NUMBER_OF_INTERFACES 1


extern char *snet_reach_labels[];

extern char *snet_reach_interfaces[];


extern snet_stream_t *SNet__reach___reach(snet_stream_t *in_buf, snet_info_t *info, int location);

#endif

